# Generated by Django 3.2.6 on 2022-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledriveapp', '0004_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folderdesc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='folder',
            name='foldername',
            field=models.CharField(max_length=20),
        ),
    ]
